include:
  - worker/docker-compose.yml
  - gateway/docker-compose.yml
  - mocks/service1/docker-compose.yml
  - mocks/service2/docker-compose.yml
  - mocks/service3/docker-compose.yml

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 3020:9090
    volumes:
      - prometheus:/prometheus
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3021:3000
    volumes:
     - grafana:/var/lib/grafana

volumes:
  grafana:
  prometheus: