{
 "title": "Tasker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{instance =~ \"(worker).*\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job)(go_goroutines{instance =~ \"(worker).*\"})",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Path Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_path_status_codes{instance =~ \"(gateway).*\"}[5m])",
     "legendFormat": "{{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Status cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(status_cache_hit{instance =~ \"(gateway).*\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "irate(status_cache_miss{instance =~ \"(gateway).*\"}[5m])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Status cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(status_cache_miss{instance =~ \"(gateway).*\"}[5m])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{instance =~ \"(gateway).*\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job)(go_goroutines{instance =~ \"(gateway).*\"})",
     "legendFormat": "Goroutines"
    }
   ]
  }
 ]
}